metallb:
  controller:
    livenessProbe:
      initialDelaySeconds: 30

    readinessProbe:
      initialDelaySeconds: 30

    resources:
      requests:
        cpu: 25m
        memory: 200Mi
      limits:
        cpu: 50m
        memory: 200Mi

  speaker:
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
