metallb:
  controller:
    resources:
      requests:
        cpu: 5m
        memory: 200Mi
      limits:
        cpu: 20m
        memory: 200Mi

  speaker:
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
