{{- range $configmapName, $configmapValues := .Values.yamlConfigFiles -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  {{- range $fileName, $fileValues := $configmapValues.files }}
  {{ $fileName }}.yaml: |
    {{ toYaml $fileValues | nindent 4 }}
  {{- end }}
{{- end }}
