external-secrets:
  crds:
    annotations:
      argocd.argoproj.io/sync-wave: "-1"

  serviceMonitor:
    enabled: true

  webhook:
    certManager:
      enabled: true
      cert:
        issuerRef:
          name: external-secrets-selfsigned
