unifi:
  service:
    main:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.1.211

  ingress:
    main:
      enabled: true
      annotations:
        ingress.kubernetes.io/protocol: https
        cert-manager.io/cluster-issuer: lucys-crib-acme
      hosts:
        - host: unifi.lucyscrib.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - unifi.lucyscrib.com
          secretName: unifi-lucys-crib-cert-acme

  resources:
    requests:
      cpu: 10m
      memory: 750Mi
    limits:
      cpu: 100m
      memory: 750Mi

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi

  mongodb:
    enabled: true

    image:
      tag: 5.0.20-debian-11-r0

    useStatefulSet: true

    nodeAffinityPreset:
      type: hard
      key: kubernetes.io/arch
      values:
        - amd64

    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 300Mi

    persistence:
      enabled: true
      size: 2Gi
