longhorn:
  defaultSettings:
    createDefaultDiskLabeledNodes: true
    defaultReplicaCount: 1

  persistence:
    defaultClassReplicaCount: 1

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lucys-crib-acme
    host: longhorn.lucyscrib.com
    tls: true
    tlsSecret: longhorn-lucys-crib-cert-acme
