kargo:
  api:
    host: kargo.lucyscrib.com

    secret:
      name: admin-creds

    argocd:
      urls:
        "": https://argocd.lucyscrib.com

    # TODO
    resources:
      {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    tls:
      enabled: false
      terminatedUpstream: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: lucys-crib-acme
      tls:
        selfSignedCert: false

  controller:
    globalCredentials:
      namespaces:
        - kargo

onepassword:
  items:
    admin-creds:
      enabled: true
      item: kargo-admin-creds
    github-app-creds:
      enabled: true
      item: kargo-github-app-creds
      labels:
        kargo.akuity.io/cred-type: git
