kargo:
  api:
    host: kargo.lucyscrib.com

    secret:
      name: admin-creds

    argocd:
      urls:
        "": https://argocd.lucyscrib.com

    # TODO
    resources:
      {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    tls:
      enabled: false
      terminatedUpstream: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: lucys-crib-acme
      tls:
        selfSignedCert: false

  controller:
    # TODO
    gitClient:
      ## @param controller.gitClient.name Specifies the name of the Kargo controller (used when authoring Git commits).
      name: "Kargo"
      ## @param controller.gitClient.email Specifies the email of the Kargo controller (used when authoring Git commits).
      email: "no-reply@kargo.io"

      signingKeySecret:
        ## @param controller.gitClient.signingKeySecret.name Specifies the name of an existing `Secret` which contains the Git user's signing key. The value should be accessible under `.data.signingKey` in the same namespace as Kargo. When the signing key is a GPG key, the GPG key's name and email address identity must match the values defined for `controller.gitClient.name` and `controller.gitClient.email`.
        name: ""
        ## @param controller.gitClient.signingKeySecret.type Specifies the type of the signing key. The currently supported and default option is `gpg`.
        type: ""

onepassword:
  items:
    admin-creds:
      enabled: true
      item: kargo-admin-creds
