apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-homelab
  annotations:
    # Sync after CRDs are created and the operator is running
    argocd.akuity.io/sync-wave: "1"
spec:
  provider:
    onepasswordSDK:
      vault: Homelab
      auth:
        serviceAccountSecretRef:
          namespace: 1password
          name: 1password-sa-token-homelab
          key: token
