apiVersion: v2
name: test
description: A Helm chart for CoreDNS k8s-gateway
type: application
version: 0.1.0

dependencies:
  - name: k8s-gateway
    repository: https://ori-edge.github.io/k8s_gateway/
    version: 2.3.0
