k8s-gateway:
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.1.253

  domain: lucyscrib.com

  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
