k8s-gateway:
  image:
    tag: v0.3.4

  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.1.253

  domain: lucyscrib.com

  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
