apiVersion: v2
name: cloudflare-tunnel
description: A Helm chart for Cloudflare Tunnel
type: application
version: 0.1.0
appVersion: 2026.1.1

dependencies:
  - name: external-secrets
    repository: file://../../charts/external-secrets
    version: 0.1.0
