cloudflare:
  tunnelName: lucyscrib

  creds:
    secretName: lucyscrib-tunnel-creds
    secretKey: credential

  origin:
    secretName: lucyscrib-tunnel-origin
    secretKey: cert.pem

  enableWarp: true

  ingress:
    unifi.lucyscrib.com:
      service: https://unifi.unifi.svc.cluster.local:8443
      originRequest:
        noTLSVerify: true

    homeassistant.lucyscrib.com:
      service: http://home-assistant.home-assistant.svc.cluster.local:8123

replicaCount: 2

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: "2023.8.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    cpu: 5m
    memory: 40Mi
  limits:
    cpu: 50m
    memory: 40Mi

nodeSelector: {}

tolerations: []

affinity: {}

onepassword:
  items:
    lucyscrib-tunnel-creds:
      enabled: true
      item: cloudflared-lucyscrib-tunnel-creds

    lucyscrib-tunnel-origin:
      enabled: true
      item: cloudflared-lucyscrib-tunnel-origin
