cloudflare:
  tunnelName: lucyscrib

  creds:
    secretName: lucyscrib-tunnel-creds
    secretKey: credential

  origin:
    secretName: lucyscrib-tunnel-origin
    secretKey: cert.pem

  enableWarp: false

  ingress:
    unifi.lucyscrib.com:
      service: http://unifi.unifi.svc.cluster.local:8443
      originRequest:
        noTLSVerify: true

replicaCount: 2

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: "2023.7.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
