image:
  repository: eclipse-mosquitto

service:
  main:
    ports:
      http:
        enabled: false
      mqtt:
        enabled: true
        port: 1883

resources:
  requests:
    cpu: 1m
    memory: 10Mi
  limits:
    cpu: 10m
    memory: 10Mi

persistence:
  config:
    enabled: true
    mountPath: /mosquitto/config/mosquitto.conf
    readOnly: true
    type: configMap
    name: mosquitto-config
    subPath: mosquitto.conf
  data:
    enabled: true
    mountPath: /mosquitto/data
    accessMode: ReadWriteOnce
    size: 1Gi

configmap:
  config:
    enabled: true
    data:
      mosquitto.conf: |
        allow_anonymous true
        listener 1883 0.0.0.0
        persistence true
        persistence_location /mosquitto/data
