apiVersion: v2
name: test
description: A Helm chart for MetalLB
type: application
version: 0.1.0

dependencies:
  - name: metallb
    repository: https://metallb.github.io/metallb
    version: 0.13.9
