image:
  repository: ghcr.io/home-assistant/home-assistant

env:
  TZ: UTC

priorityClassName: critical

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 1Gi
  configuration:
    enabled: true
    mountPath: /config/configuration.yaml
    readOnly: true
    type: configMap
    name: home-assistant-configuration
    subPath: configuration.yaml
  secrets:
    enabled: true
    mountPath: /config/secrets.yaml
    readOnly: true
    type: secret
    name: home-assistant-secrets
    subPath: secrets.yaml

configmap:
  configuration:
    enabled: true
    data:
      configuration.yaml: |
        default_config:

        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.42.0.0/16

        automation: !include automations.yaml

        rest_command:
          brewers_friend_publish:
            url: "https://log.brewersfriend.com/stream/{{ api_key }}"
            method: POST
            content_type: "application/json; charset=utf-8"
            payload: |
              {
                "name": "HomeAssistant {{ fermenter_name }}",
                "report_source": "HomeAssistant",
                "temp": "{{ temperature }}",
                "temp_unit": "F",
                "gravity": "{{ specific_gravity }}",
                "gravity_unit": "G"
              }

          pagerduty_trigger:
            url: "https://events.pagerduty.com/v2/enqueue"
            method: POST
            content_type: "application/json; charset=utf-8"
            payload: |
              {
                "routing_key": "{{ pagerduty_routing_key }}",
                "event_action": "trigger",
                "dedup_key": "{{ alert_key }}",
                "payload": {
                  "summary": "{{ summary }}",
                  "severity": "{{ severity }}",
                  "class": "{{ class }}",
                  "group": "{{ group }}",
                  "component": "{{ component }}",
                  "source": "homeassistant.lucyscrib.com"
                }
              }

          pagerduty_resolve:
            url: "https://events.pagerduty.com/v2/enqueue"
            method: POST
            content_type: "application/json; charset=utf-8"
            payload: |
              {
                "routing_key": "{{ pagerduty_routing_key }}",
                "event_action": "resolve",
                "dedup_key": "{{ alert_key }}"
              }

          pagerduty_entity_trigger:
            url: "https://events.pagerduty.com/v2/enqueue"
            method: POST
            content_type: "application/json; charset=utf-8"
            payload: |
              {
                "routing_key": "{{ pagerduty_routing_key }}",
                "event_action": "trigger",
                "dedup_key": "{{ type }}:{{ entity_id }}",
                "payload": {
                  "summary": "{{ summary }}",
                  "severity": "{{ severity }}",
                  "class": "{{ type }}",
                  "group": "{{ area_name(entity_id) }}",
                  "component": "{{ entity_id }}",
                  "source": "homeassistant.lucyscrib.com"
                },
                "links": [
                  {
                    "href": "https://homeassistant.lucyscrib.com/history?entity_id={{ entity_id }}",
                    "text": "{{ state_attr(entity_id, 'friendly_name') }}"
                  }
                ]
              }

          pagerduty_entity_resolve:
            url: "https://events.pagerduty.com/v2/enqueue"
            method: POST
            content_type: "application/json; charset=utf-8"
            payload: |
              {
                "routing_key": "{{ pagerduty_routing_key }}",
                "event_action": "resolve",
                "dedup_key": "{{ type }}:{{ entity_id }}"
              }

service:
  main:
    ports:
      http:
        port: 8123

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lucys-crib-acme
    hosts:
      - host: homeassistant.lucyscrib.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - homeassistant.lucyscrib.com
        secretName: homeassistant-lucys-crib-cert-acme

onepassword:
  items:
    home-assistant-secrets:
      enabled: true
      item: home-assistant-secrets
