image:
  repository: ghcr.io/home-assistant/home-assistant

env:
  TZ: UTC

priorityClassName: critical

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 1Gi
  configuration:
    enabled: true
    mountPath: /config/configuration.yaml
    readOnly: true
    type: configMap
    name: home-assistant-configuration
    subPath: configuration.yaml
  static-config:
    enabled: true
    mountPath: /config/static-config
    readOnly: true
    type: configMap
    name: static-config
  secrets:
    enabled: true
    mountPath: /config/secrets.yaml
    readOnly: true
    type: secret
    name: home-assistant-secrets
    subPath: secrets.yaml
  blueprints-automation:
    enabled: true
    mountPath: /config/blueprints/automation/custom
    readOnly: true
    type: configMap
    name: blueprints-automation
  dbus:
    enabled: true
    mountPath: /run/dbus
    readOnly: true
    type: hostPath
    hostPath: /run/dbus

configmap:
  configuration:
    enabled: true
    data:
      configuration.yaml: |
        default_config:

        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.42.0.0/16

        automation: !include automations.yaml
        automation static: !include static-config/automations.yaml

        rest_command: !include static-config/rest_command.yaml

        template: !include static-config/templates.yaml

yamlConfigFiles:
  static-config:
    files:
      automations: |
        - id: living_room_smoke_alert
          alias: Living Room Smoke Alert
          use_blueprint:
            path: custom/binary_alert.yaml
            input:
              sensor: binary_sensor.living_room_smoke_co_detector_smoke_detected
              alert_message: Smoke detected in living room
              alert_severity: critical
              clear_time:
                hours: 0
                minutes: 15
                seconds: 0
              pagerduty_routing_key: !secret pagerduty_routing_key

        - id: living_room_co_alert
          alias: Living Room CO Alert
          use_blueprint:
            path: custom/binary_alert.yaml
            input:
              sensor: binary_sensor.living_room_smoke_co_detector_carbon_monoxide_detected
              alert_message: Carbon monoxide detected in living room
              alert_severity: critical
              clear_time:
                hours: 0
                minutes: 15
                seconds: 0
              pagerduty_routing_key: !secret pagerduty_routing_key

        - id: kitchen_sink_leak_alert
          alias: Kitchen Sink Leak Alert
          use_blueprint:
            path: custom/binary_alert.yaml
            input:
              sensor: binary_sensor.kitchen_sink_water_sensor_water_leak_detected
              alert_message: Leak detected under kitchen sink
              alert_severity: critical
              clear_time:
                hours: 1
                minutes: 0
                seconds: 0
              pagerduty_routing_key: !secret pagerduty_routing_key

        - id: basement_water_heater_leak_alert
          alias: Basement Water Heater Leak Alert
          use_blueprint:
            path: custom/binary_alert.yaml
            input:
              sensor: binary_sensor.basement_water_heater_water_sensor_water_leak_detected
              alert_message: Leak detected at basement water heater
              alert_severity: critical
              clear_time:
                hours: 1
                minutes: 0
                seconds: 0
              pagerduty_routing_key: !secret pagerduty_routing_key

        - id: zwave_nodes_unhealthy_alert
          alias: ZWave Nodes Unhealthy Alert
          use_blueprint:
            path: custom/binary_alert.yaml
            input:
              sensor: binary_sensor.zwave_nodes_unhealthy
              alert_message: One or more ZWave nodes are unhealthy
              alert_severity: warning
              clear_time:
                hours: 0
                minutes: 1
                seconds: 0
              pagerduty_routing_key: !secret pagerduty_routing_key

        - id: tilt_green_brewers_friend_publish
          alias: Tilt Green Brewer's Friend Publish
          use_blueprint:
            path: custom/brewers_friend_publish.yaml
            input:
              fermenter_name: Green
              temperature_sensor: sensor.tilt_green_temperature
              specific_gravity_sensor: sensor.tilt_green_specific_gravity
              api_key: !secret brewers_friend_api_key

      rest_command: |
        brewers_friend_publish:
          url: "https://log.brewersfriend.com/stream/{{ api_key }}"
          method: POST
          content_type: "application/json; charset=utf-8"
          payload: |
            {
              "name": "HomeAssistant {{ fermenter_name }}",
              "report_source": "HomeAssistant",
              "temp": "{{ temperature }}",
              "temp_unit": "F",
              "gravity": "{{ specific_gravity }}",
              "gravity_unit": "G"
            }

        pagerduty_trigger:
          url: "https://events.pagerduty.com/v2/enqueue"
          method: POST
          content_type: "application/json; charset=utf-8"
          payload: |
            {
              "routing_key": "{{ pagerduty_routing_key }}",
              "event_action": "trigger",
              "dedup_key": "{{ alert_key }}",
              "payload": {
                "summary": "{{ summary }}",
                "severity": "{{ severity }}",
                "class": "{{ class }}",
                "group": "{{ group }}",
                "component": "{{ component }}",
                "source": "homeassistant.lucyscrib.com"
              }
            }

        pagerduty_resolve:
          url: "https://events.pagerduty.com/v2/enqueue"
          method: POST
          content_type: "application/json; charset=utf-8"
          payload: |
            {
              "routing_key": "{{ pagerduty_routing_key }}",
              "event_action": "resolve",
              "dedup_key": "{{ alert_key }}"
            }

        pagerduty_entity_trigger:
          url: "https://events.pagerduty.com/v2/enqueue"
          method: POST
          content_type: "application/json; charset=utf-8"
          payload: |
            {
              "routing_key": "{{ pagerduty_routing_key }}",
              "event_action": "trigger",
              "dedup_key": "{{ type }}:{{ entity_id }}",
              "payload": {
                "summary": "{{ summary }}",
                "severity": "{{ severity }}",
                "class": "{{ type }}",
                "group": "{{ area_name(entity_id) }}",
                "component": "{{ entity_id }}",
                "source": "homeassistant.lucyscrib.com"
              },
              "links": [
                {
                  "href": "https://homeassistant.lucyscrib.com/history?entity_id={{ entity_id }}",
                  "text": "{{ state_attr(entity_id, 'friendly_name') }}"
                }
              ]
            }

        pagerduty_entity_resolve:
          url: "https://events.pagerduty.com/v2/enqueue"
          method: POST
          content_type: "application/json; charset=utf-8"
          payload: |
            {
              "routing_key": "{{ pagerduty_routing_key }}",
              "event_action": "resolve",
              "dedup_key": "{{ type }}:{{ entity_id }}"
            }

      templates: |
        - binary_sensor:
          - name: ZWave Nodes Unhealthy
            device_class: problem
            state: >
              {{
                states |
                selectattr("entity_id", "search", "node_status") |
                selectattr('state', 'in', ['dead', 'unavailable', 'unknown']) |
                map(attribute='entity_id') |
                list |
                count
              }}

  blueprints-automation:
    files:
      binary_alert: |
        blueprint:
          domain: automation
          name: Binary Sensor Alert
          description: Send alert based on a binary sensor
          input:
            sensor:
              name: Sensor
              description: The sensor to trigger the alert
              selector:
                entity:
                  domain: binary_sensor
            alert_message:
              name: Alert Message
              description: The message to display in the alert
            alert_severity:
              name: Alert Severity
              description: The severity level of the alert
              selector:
                select:
                  options:
                    - critical
                    - error
                    - warning
                    - info
            clear_time:
              name: Clear Time
              description: The duration that the sensor must be off before clearing the alert
              selector:
                duration:
            pagerduty_routing_key:
              name: PagerDuty Routing Key
              description: The key of the PagerDuty integration to which to route the alerts
              selector:
                text:

        variables:
          entity_id: !input sensor
          alert_type: "{{ state_attr(entity_id, 'device_class') }}"

        trigger:
          - platform: state
            entity_id: !input sensor
            to: "on"

        action:
          - service: rest_command.pagerduty_entity_trigger
            data:
              pagerduty_routing_key: !input pagerduty_routing_key
              entity_id: !input sensor
              type: "{{ alert_type }}"
              summary: !input alert_message
              severity: !input alert_severity
          - wait_for_trigger:
              - platform: state
                entity_id:
                  - !input sensor
                to: "off"
                for: !input clear_time
            continue_on_timeout: false
          - service: rest_command.pagerduty_entity_resolve
            data:
              pagerduty_routing_key: !input pagerduty_routing_key
              entity_id: !input sensor
              type: "{{ alert_type }}"

      brewers_friend_publish: |
        blueprint:
          domain: automation
          name: Brewer's Friend Publish
          description: Publish temperature and specific gravity data to Brewer's Friend
          input:
            fermenter_name:
              name: Fermenter Name
              description: The name that will appear for the device in Brewer's Friend
              selector:
                text:
            temperature_sensor:
              name: Temperature Sensor
              description: The sensor to get temperature data from
              selector:
                entity:
                  domain: sensor
                  device_class: temperature
            specific_gravity_sensor:
              name: Specific Gravity Sensor
              description: The sensor to get specific gravity data from
              selector:
                entity:
                  domain: sensor
            api_key:
              name: Brewer's Friend API Key
              description: The API key to use to authenticate with Brewer's Friend
              selector:
                text:

        variables:
          fermenter_name: !input fermenter_name
          temperature_sensor: !input temperature_sensor
          specific_gravity_sensor: !input specific_gravity_sensor
          api_key: !input api_key

        trigger:
          - platform: time_pattern
            minutes: "/20"

        condition:
          - condition: and
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: "{{ temperature_sensor }}"
                    state: unavailable
              - condition: not
                conditions:
                  - condition: state
                    entity_id: "{{ specific_gravity_sensor }}"
                    state: unavailable

        action:
          - service: rest_command.brewers_friend_publish
            data:
              api_key: "{{ api_key }}"
              fermenter_name: "{{ fermenter_name }}"
              temperature: "{{ states(temperature_sensor) }}"
              specific_gravity: "{{ states(specific_gravity_sensor) }}"

service:
  main:
    ports:
      http:
        port: 8123

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lucys-crib-acme
    hosts:
      - host: homeassistant.lucyscrib.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - homeassistant.lucyscrib.com
        secretName: homeassistant-lucys-crib-cert-acme

onepassword:
  items:
    home-assistant-secrets:
      enabled: true
      item: home-assistant-secrets
