unifi:
  service:
    main:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.1.211

  ingress:
    main:
      enabled: true
      annotations:
        ingress.kubernetes.io/protocol: https
      hosts:
        - host: unifi.lucyscrib.com
          paths:
            - path: /
              pathType: Prefix

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi

  mongodb:
    enabled: true
    persistence:
      enabled: true
      size: 2Gi
