unifi:
  ingress:
    main:
      enabled: true
      hosts:
        - host: unifi.lucyscrib.com
          paths:
            - path: /
              pathType: ImplementationSpecific
              service:
                port: 8080

  mongodb:
    enabled: true
    persistence:
      enabled: true
      size: 2Gi
