image:
  repository: ghcr.io/esphome/esphome

securityContext:
  privileged: true

env:
  USERNAME:
    valueFrom:
      secretKeyRef:
        name: login-creds
        key: username
  PASSWORD:
    valueFrom:
      secretKeyRef:
        name: login-creds
        key: password

persistence:
  config:
    enabled: true
  usb:
    enabled: true
    mountPath: /dev/bus/usb
    type: hostPath
    hostPath: /dev/bus/usb

service:
  main:
    ports:
      http:
        port: 6053

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lucys-crib-acme
    hosts:
      - host: esphome.lucyscrib.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - esphome.lucyscrib.com
        secretName: esphome-lucys-crib-cert-acme

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    memory: 50Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: lucyscrib.com/esphome-flasher
              operator: Exists

onepassword:
  items:
    login-creds:
      enabled: true
      item: esphome-creds
