image:
  repository: ghcr.io/esphome/esphome

env:
  USERNAME:
    valueFrom:
      secretKeyRef:
        name: login-creds
        key: username
  PASSWORD:
    valueFrom:
      secretKeyRef:
        name: login-creds
        key: password

persistence:
  config:
    enabled: true
    size: 10Gi
  secrets:
    enabled: true
    mountPath: /config/secrets.yaml
    readOnly: true
    type: secret
    name: esphome-secrets
    subPath: secrets.yaml
  bluetooth-proxy-brewery:
    enabled: true
    mountPath: /config/bluetooth-proxy-brewery.yaml
    readOnly: true
    type: configMap
    name: esphome-bluetooth-proxy-brewery
    subPath: bluetooth-proxy-brewery.yaml

configmap:
  bluetooth-proxy-brewery:
    enabled: true
    data:
      bluetooth-proxy-brewery.yaml: |
        substitutions:
          name: bluetooth-proxy-brewery

        esphome:
          name: ${name}

        esp32:
          variant: esp32
          framework:
            type: esp-idf

        wifi:
          ssid: !secret wifi_ssid
          password: !secret wifi_password
          use_address: 10.0.0.191

        # Enable logging
        logger:

        # Enable Home Assistant API
        api:

        ota:
          platform: esphome
          password: !secret bluetooth_proxy_brewery_password

        esp32_ble_tracker:

        bluetooth_proxy:
          active: true

resources:
  requests:
    cpu: 10m
    memory: 250Mi
  limits:
    memory: 2Gi

service:
  main:
    ports:
      http:
        port: 6052

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lucys-crib-acme
    hosts:
      - host: esphome.lucyscrib.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - esphome.lucyscrib.com
        secretName: esphome-lucys-crib-cert-acme

external-secrets:
  onepassword:
    secrets:
      esphome-creds:
        enabled: true
        keys:
          username:
            item: esphome-creds
            field: username
          password:
            item: esphome-creds
            field: password

      esphome-secrets:
        enabled: true
        keys:
          wifi_ssid:
            item: "lucys-things-network"
            field: "network name"
          wifi_password:
            item: "lucys-things-network"
            field: "wireless network password"
          bluetooth_proxy_brewery_password:
            item: "bluetooth-proxy-brewery"
            field: "password"
        templateKeys:
          secrets.yaml: |
            wifi_ssid: {{ .wifi_ssid }}
            wifi_password: {{ .wifi_password }}
            bluetooth_proxy_brewery_password: {{ .bluetooth_proxy_brewery_password }}
