image:
  repository: ghcr.io/esphome/esphome

env:
  USERNAME:
    valueFrom:
      secretKeyRef:
        name: login-creds
        key: username
  PASSWORD:
    valueFrom:
      secretKeyRef:
        name: login-creds
        key: password

persistence:
  config:
    enabled: true
    size: 10Gi

service:
  main:
    ports:
      http:
        port: 6052

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lucys-crib-acme
    hosts:
      - host: esphome.lucyscrib.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - esphome.lucyscrib.com
        secretName: esphome-lucys-crib-cert-acme

onepassword:
  items:
    login-creds:
      enabled: true
      item: esphome-creds
