{{- range $projectName, $project := .Values.projects }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-creds
  namespace: {{ include "kargo.projectName" $projectName }}
spec:
  refreshInterval: 6h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-homelab
  target:
    creationPolicy: Owner
    name: dockerhub-creds
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: image
      data:
        repoURL: docker.io
        repoURLIsRegex: "true"
  data:
    - secretKey: username
      remoteRef:
        key: kargo-dockerhub-creds/username
    - secretKey: password
      remoteRef:
        key: kargo-dockerhub-creds/password
{{- end }}
