{{- range $projectName, $project := .Values.projects }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-creds
  namespace: {{ include "kargo.projectName" $projectName }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-homelab
  target:
    creationPolicy: Owner
    name: dockerhub-creds
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: image
  data:
    - secretKey: username
      remoteRef:
        key: kargo-dockerhub-creds/username
    - secretKey: password
      remoteRef:
        key: kargo-dockerhub-creds/password
    - secretKey: repoURL
      remoteRef:
        key: kargo-dockerhub-creds/repoURL
    - secretKey: repoURLIsRegex
      remoteRef:
        key: kargo-dockerhub-creds/repoURLIsRegex
{{- end }}
