{{- range $projectName, $project := .Values.projects }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-creds
  namespace: {{ include "kargo.projectName" $projectName }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-homelab
  target:
    creationPolicy: Owner
    name: github-app-creds
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data:
        repoURL: https://github.com/apt-itude/homelab-kubernetes.git
  data:
    - secretKey: githubAppID
      remoteRef:
        key: kargo-github-app-creds/githubAppID
    - secretKey: githubAppInstallationID
      remoteRef:
        key: kargo-github-app-creds/githubAppInstallationID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: kargo-github-app-creds/githubAppPrivateKey
{{- end }}
