{{- range $projectName, $project := .Values.projects }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: {{ include "kargo.projectName" $projectName }}
  annotations:
    # This annotation ensures Projects (Namespaces) are created first when deployed via Argo CD
    argocd.argoproj.io/sync-wave: "-1"
{{- end }}
