longhorn:
  defaultSettings:
    createDefaultDiskLabeledNodes: true
    defaultReplicaCount: 1
    concurrentAutomaticEngineUpgradePerNodeLimit: 3

  defaultBackupStore:
    # -- Endpoint used to access the default backupstore. (Options: "NFS", "CIFS", "AWS", "GCP", "AZURE")
    backupTarget: s3://homelab-volume-backups@us-east-2/longhorn
    # -- Name of the Kubernetes secret associated with the default backup target.
    backupTargetCredentialSecret: aws-creds

  persistence:
    defaultClassReplicaCount: 1

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lucys-crib-acme
    host: longhorn.lucyscrib.com
    tls: true
    tlsSecret: longhorn-lucys-crib-cert-acme

external-secrets:
  onepassword:
    secrets:
      aws-creds:
        enabled: true
        keys:
          AWS_ACCESS_KEY_ID:
            item: longhorn-aws-creds
            field: AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY:
            item: longhorn-aws-creds
            field: AWS_SECRET_ACCESS_KEY
