kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi

    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: lucys-crib-acme

      hosts:
        - prometheus.lucyscrib.com

      tls:
        - hosts:
            - prometheus.lucyscrib.com
          secretName: prometheus-lucys-crib-cert-acme

  grafana:
    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: lucys-crib-acme

      hosts:
        - grafana.lucyscrib.com

      tls:
        - hosts:
            - grafana.lucyscrib.com
          secretName: grafana-lucys-crib-cert-acme

    serviceMonitor:
      enabled: false

  alertmanager:
    enabled: false

  defaultRules:
    create: false

  kubeApiServer:
    enabled: false

  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false
