kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 14d
      retentionSize: 45GB
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi

    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: lucys-crib-acme

      hosts:
        - prometheus.lucyscrib.com

      tls:
        - hosts:
            - prometheus.lucyscrib.com
          secretName: prometheus-lucys-crib-cert-acme

  grafana:
    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: lucys-crib-acme

      hosts:
        - grafana.lucyscrib.com

      tls:
        - hosts:
            - grafana.lucyscrib.com
          secretName: grafana-lucys-crib-cert-acme

    serviceMonitor:
      enabled: false

  alertmanager:
    enabled: false

  defaultRules:
    create: true
    rules:
      alertmanager: false
      etcd: false
      configReloaders: false
      general: true
      k8s: true
      kubeApiserverAvailability: false
      kubeApiserverBurnrate: false
      kubeApiserverHistogram: false
      kubeApiserverSlos: false
      kubeControllerManager: false
      kubelet: false
      kubeProxy: false
      kubePrometheusGeneral: false
      kubePrometheusNodeRecording: false
      kubernetesApps: false
      kubernetesResources: false
      kubernetesStorage: false
      kubernetesSystem: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
      kubeStateMetrics: false
      network: false
      node: true
      nodeExporterAlerting: false
      nodeExporterRecording: false
      prometheus: false
      prometheusOperator: false
      windows: false

  kubeApiServer:
    enabled: false

  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false
